"""Regenerate results_tier1.md from the cache_tier1/*.npz checkpoints.

Hand-maintained result tables go stale silently, so the prose and the numbers
are both emitted here. Rerun after extending any cache:

    SR_CorrNet_SS/.venv/Scripts/python.exe report_tier1.py
"""

import pathlib

import numpy as np
from scipy import stats

C = pathlib.Path("cache_tier1")


def load(name):
    with np.load(C / name, allow_pickle=True) as z:
        return {k: z[k] for k in z.files}


def paired(a, b, n, key_a="base", key_b="base"):
    ka, kb = list(a[f"keys_{n}"]), list(b[f"keys_{n}"])
    sb = set(kb)
    common = [k for k in ka if k in sb]
    xa = a[f"{key_a}_{n}"][[ka.index(k) for k in common]]
    xb = b[f"{key_b}_{n}"][[kb.index(k) for k in common]]
    d = xb - xa
    se = d.std(ddof=1) / np.sqrt(len(d))
    return (
        xa.mean(),
        xb.mean(),
        d.mean(),
        stats.t.ppf(0.975, len(d) - 1) * se,
        stats.ttest_rel(xb, xa).pvalue,
        len(d),
    )


def fmt(p):
    return "<0.001" if p < 0.001 else f"{p:.3f}"


L = []
A = L.append

A("# Tier 1 results — routing, mixture consistency, offset ensembling")
A("")
A("**Generated by `report_tier1.py` from `cache_tier1/*.npz`. Do not hand-edit — rerun the script.**")
A("")
A("Covers Tier 1 of the improvements roadmap. Counting is out of")
A("scope here: every number below uses the **oracle speaker count** (`n_spks=N` is passed), so")
A("this measures separation quality only and is unaffected by the counting question.")
A("")

# ---------------------------------------------------------------- method
A("## What the metric is (and is not)")
A("")
A("**SI-SNRi in dB — an IMPROVEMENT over the unprocessed mixture, not an absolute SDR.**")
A("Computed with the authors' own `PIT_SISNRi(scale_inv=True)` from")
A("`sr_corrnet/models/SR_CorrNet_SS/loss.py`, not a reimplementation.")
A("")
A("**Do NOT compare these against the BSS_Eval SDR/SIR/SAR in `results_bleed.md`** — those are")
A("absolute, these are improvements. That substitution is one step away from a wrong conclusion.")
A("")
A("**Every comparison is PAIRED on identical mixture keys** (the intersection is computed, not")
A("assumed). This matters more than sample size here: per-mixture difficulty carries a 1.5–4 dB")
A("standard deviation, so an unpaired test at n=100 resolves ~±0.4 dB, while the paired delta")
A("cancels that variance and resolves ~±0.03 dB. CIs are t-based 95%; p is a two-sided paired")
A("t-test.")
A("")
A("**Harness cross-check:** the `var-2-5spk` baseline column reproduces the verified baseline's headline")
A("numbers exactly (23.39 / 23.84 / 22.20 / 20.57 at N=2/3/4/5, n=100), which is independent")
A("evidence this harness agrees with the already-verified `benchmark.py`.")
A("")

# ---------------------------------------------------------------- routing
A("## 1.1 Checkpoint routing — VERDICT: route N=2 to `fix-2spk-l-dm`, nothing else")
A("")
A("Dataset: **official WSJ0-mix `tt` (IN DOMAIN)**, oracle count. Baseline is")
A("`shinuh/sr-corrnet-ss-1ch-wsj-var-2-5spk` (the currently shipped checkpoint).")
A("A positive Δ means **the challenger beats the current checkpoint**.")
A("")
A("| N | challenger checkpoint | var-2-5spk | challenger | paired Δ (dB) | 95% CI | p | n |")
A("|---|---|---|---|---|---|---|---|")

var25 = load("wsj0_var25.npz")
for n, label, f in [
    (2, "`fix-2spk`", "wsj0_fix2.npz"),
    (2, "`fix-2spk-l-dm`", "wsj0_fix2ldm.npz"),
    (2, "`var-2-3spk`", "wsj0_var23.npz"),
    (3, "`var-2-3spk`", "wsj0_var23.npz"),
]:
    if not (C / f).exists():
        continue
    b = load(f)
    if f"base_{n}" not in b:
        continue
    ma, mb, d, ci, p, nn = paired(var25, b, n)
    A(f"| {n} | {label} | {ma:.2f} | {mb:.2f} | **{d:+.3f}** | ±{ci:.3f} | {fmt(p)} | {nn} |")

A("")
A("### Verdict in words")
A("")
A("**The roadmap's premise — \"specialized models beat general ones at their own count\" — is")
A("FALSE here for three of the four checkpoints.** Only one routing rule survives:")
A("")
A("- **`fix-2spk-l-dm` at N=2: +0.57 dB, p<0.001. SHIP THIS.** Stable across sample sizes")
A("  (+0.529 at n=25 → +0.570 at n=100), so it is not a small-sample artifact.")
A("- **`fix-2spk` at N=2: −1.15 dB. Do NOT route.** The plain specialized 2-speaker model is")
A("  *worse* than the general one.")
A("- **`var-2-3spk`: −0.90 at N=2, −1.91 at N=3. Do NOT route.**")
A("")
A("**What this rules out, and what it implies.** The two `fix-2spk*` checkpoints differ only in")
A("being large + dynamic-mixing. Plain specialization LOSES 1.15 dB; specialization + DM WINS")
A("0.57 dB. So the win is attributable to **dynamic mixing, not to specialization** — which is")
A("independent, measured support for Tier 2.1 (fine-tune with DM on), and evidence that the")
A("remaining Tier 1 ceiling is low.")
A("")
A("### The `var-2-3spk` N=3 failure is BIMODAL — a tail, not a slope")
A("")
A("Worth recording because the mean hides it. Per-mixture at n=25, `var-2-3spk` minus")
A("`var-2-5spk` at N=3:")
A("")
A("- **13/25 mixtures are a tie** (within ±1 dB); **11/25 fail catastrophically** (−3 to −15 dB).")
A("- **median Δ = −0.83 dB, mean Δ = −3.67 dB.** The mean is dragged entirely by the tail.")
A("- `var-2-3spk`'s absolute scores collapse as low as **7.5 dB** on the failures.")
A("")
A("This is a **reliability** failure, not a quality gap — so no sample size would rehabilitate")
A("it. It is the strongest reason not to route N=3.")
A("")

# ---------------------------------------------------- mixture consistency
A("## 1.2 Mixture consistency — VERDICT: ship it, but it is worth ~+0.4 dB at N=2, ~0 at N=5")
A("")
A("Δ = SI-SNRi(with MC) − SI-SNRi(without), **same forward pass** (so it costs no GPU and")
A("carries no inference-time cost). Checkpoint `var-2-5spk`, oracle count.")
A("")
A("| dataset | domain | N | baseline | +MC | paired Δ (dB) | 95% CI | p | n |")
A("|---|---|---|---|---|---|---|---|---|")
for label, dom, f in (
    ("WSJ0-mix `tt`", "**in**", "wsj0_var25.npz"),
    ("LibriSpeech dev-clean", "**out**", "libri_var25.npz"),
):
    if not (C / f).exists():
        continue
    z = load(f)
    for n in sorted(int(k.split("_")[1]) for k in z if k.startswith("base_")):
        ma, mb, d, ci, p, nn = paired(z, z, n, "base", "mc")
        A(f"| {label} | {dom} | {n} | {ma:.2f} | {mb:.2f} | **{d:+.3f}** | ±{ci:.3f} | {fmt(p)} | {nn} |")

A("")
A("### The implementation trap — READ THIS BEFORE TOUCHING `mixture_consistency()`")
A("")
A("**The textbook formula `s += (y - sum(s))/N` is WRONG for this model as written.**")
A("Measured (`probe_output_scale.py`), not assumed:")
A("")
A("- This model is trained with a **scale-invariant loss, so its output gain is arbitrary**.")
A("  Raw streams are ~87× the true sources and **polarity-inverted** (best-fit gain ≈ **−0.011**,")
A("  note the minus sign).")
A("- Therefore `sum(est)` does **not** approximate the mixture in any domain — measured")
A("  `||y_norm − sum(est)|| / ||y_norm||` = **9.6**, i.e. the naive residual is ~87× too large")
A("  and annihilates the estimates.")
A("- **SI-SNR would not catch this.** Being scale invariant, a wrong-domain `y` reads as an")
A("  ordinary regression, not as a bug. This is the same class of silent failure as the")
A("  clipping bug.")
A("")
A("**The fix that makes it work:** the arbitrary gain is *global* — identical across streams to")
A("within 1% (measured spread max/min = 1.00–1.01 at N=2/3/4). So one least-squares scalar")
A("against the mixture restores consistency, and `mix` is available at test time (using the")
A("references would be cheating). The blind estimate matches the reference-derived gain to 4")
A("decimals (−0.011469 vs −0.01147).")
A("")
A("**Bonus finding — `separate.py`'s shared-gain rescale is now VERIFIED, not assumed.** Because")
A("the gain really is global, one shared gain across streams genuinely preserves relative speaker")
A("levels. This was previously asserted; it is now measured.")
A("")
A("### Verdict in words")
A("")
A("Real, free, and always non-negative in domain — but **smaller than the +0.7 dB the paper")
A("reports**, and it decays sharply with N (+0.42 → +0.04 from N=2 → N=5). Expected: the")
A("residual is only ~3% for a model this strong, so there is little left to redistribute.")
A("")
A("**Out of domain it is worth ~nothing above N=3** (+0.38 at N=2, but −0.003 at N=4 and +0.012")
A("at N=5 — the N=4 point is a *negative* point estimate). Do not assume the in-domain gain")
A("transfers.")
A("")

# ------------------------------------------------------------- ensembling
if (C / "ensemble.npz").exists():
    z = load("ensemble.npz")
    counts = sorted(int(k.split("_")[1]) for k in z if k.startswith("ens_"))
    has_mc = any(f"ensmc_{n}" in z for n in counts)
    A("## 1.3 Offset ensembling — VERDICT: real and grows with N, but costs 4×. NOT shipped")
    A("")
    A("4 input offsets (0/16/32/48 samples), streams permutation- and sign-matched across runs,")
    A("then averaged. WSJ0 `tt`, `var-2-5spk`, oracle count. **Costs 4× inference.**")
    A("`ens+MC` applies mixture consistency on top of the ensemble, to test whether they stack.")
    A("")
    A("| N | single | ensemble | paired Δ (dB) | 95% CI | p | ens+MC | Δ ens+MC | n | resolved? |")
    A("|---|---|---|---|---|---|---|---|---|---|")
    unresolved, sig = [], []
    for n in counts:
        ma, mb, d, ci, p, nn = paired(z, z, n, "single", "ens")
        excl = abs(d) > ci  # does the 95% CI exclude zero?
        (sig if excl else unresolved).append(n)
        if f"ensmc_{n}" in z:
            _, m2, d2, ci2, _, _ = paired(z, z, n, "single", "ensmc")
            mc_cell = f"{m2:.2f} | **{d2:+.3f}** ±{ci2:.3f}"
        else:
            mc_cell = "— | —"
        flag = "yes" if excl else "**NO — CI spans 0**"
        A(f"| {n} | {ma:.2f} | {mb:.2f} | **{d:+.3f}** | ±{ci:.3f} | {fmt(p)} | {mc_cell} | {nn} | {flag} |")
    A("")
    A("### Is it worth 4× inference? Only at N≥3 — and only if the RTF budget allows")
    A("")
    A(f"Counts whose 95% CI excludes zero: **{sig or 'none'}**. Counts still unresolved: "
      f"**{unresolved or 'none'}**.")
    A("")
    A("The decision is not \"does ensembling help\" but **\"does it help on top of mixture")
    A("consistency, which is free?\"** MC alone is the thing to beat:")
    A("")
    A("| N | ens only | MC only (free) | ens+MC | what 4× inference actually buys over MC |")
    A("|---|---|---|---|---|")
    for n in counts:
        _, _, d_ens, ci_e, p_e, nn = paired(z, z, n, "single", "ens")
        mc_only = var25[f"mc_{n}"].mean() - var25[f"base_{n}"].mean()
        if f"ensmc_{n}" in z:
            _, _, d_em, ci_m, _, _ = paired(z, z, n, "single", "ensmc")
            buys = d_em - mc_only
            verdict = "**nothing — MC alone is better**" if buys <= 0.01 else f"**{buys:+.2f}**"
            em_cell = f"{d_em:+.3f}"
        else:
            em_cell, verdict = "— not run", "**unknown**"
        ens_cell = f"{d_ens:+.3f}" + (" (ns)" if abs(d_ens) <= ci_e else "")
        A(f"| {n} | {ens_cell} | {mc_only:+.3f} | {em_cell} | {verdict} | ")
    A("")
    A("**They do stack at N=3/4/5** (roughly additively), but the two mechanisms trade places as N")
    A("rises: MC does all the work at N=2 and almost none at N=5, while ensembling does the")
    A("reverse. **At N=2 ensembling is strictly pointless** — `ens+MC` (+0.411) is no better than")
    A("MC alone (+0.422) and costs 4× inference for it.")
    A("")
    A("### The gain grows with N — now confirmed at n=100, and mechanistically expected")
    A("")
    A("Ensemble-only delta at n=100: **+0.042 → +0.247 → +0.431 → +0.486** at N=2/3/4/5 — the")
    A("mirror image of MC (**+0.42 → +0.19 → +0.08 → +0.04**), which shrinks with N.")
    A("")
    A("That is consistent with `results_bleed.md`'s finding that the error is **SAR-type")
    A("(artifacts)**: artifacts are partly stochastic across offsets, so they cancel under")
    A("averaging while the signal reinforces. High-N mixtures have the most artifacts and the most")
    A("to gain. **The growth is real but it plateaus at the top end** (+0.431 → +0.486 from N=4 to")
    A("N=5, not the continued climb the n=25 pass suggested).")
    A("")
    A("### ⚠ n=25 overestimated the ensemble at EVERY count — the cautionary tale of this document")
    A("")
    A("| N | n=25 said | n=100 says | error |")
    A("|---|---|---|---|")
    for n, old in ((2, 0.204), (3, 0.345), (4, 0.587), (5, 0.767)):
        if f"ens_{n}" not in z:
            continue
        new = (z[f"ens_{n}"] - z[f"single_{n}"]).mean()
        A(f"| {n} | {old:+.3f} | {new:+.3f} | **{new - old:+.3f}** |")
    A("")
    A("**The bias is systematic and one-directional — every count overestimated, by 0.10–0.28 dB.**")
    A("At N=2 the n=25 figure was **+0.204 with a deceptively tight ±0.030 CI**, which looked like")
    A("a clean win; at n=100 it is **+0.042 ± 0.241**, spanning zero.")
    A("")
    A("**Root cause: `sorted(keys)[:limit]` is not a random sample.** WSJ0-mix keys lead with a")
    A("speaker id, so the alphabetically-first mixtures all share a leading speaker (`050`), and")
    A("the first 25 are nearly a single session (`050a05*`). That subset is far more homogeneous")
    A("than the corpus. Two lessons:")
    A("")
    A("1. **A tight CI at small n is not evidence of a real effect** — it can mean the sample was")
    A("   unrepresentative. The pairing trick that made n=25 sufficient elsewhere is weakest here,")
    A("   because two *different configurations* disagree per-mixture far more than one")
    A("   configuration disagrees with itself, giving the ensemble deltas heavy tails n=25 hid.")
    A("2. **Use `--seed` for anything new.** `tier1_eval.py --seed N` draws a random sample")
    A("   (the same seed gives the same mixtures across checkpoints, preserving pairing).")
    A("")
    A("**This did NOT invalidate the shipped wins — see \"Sampling\" below, where a random sample")
    A("makes both of them slightly LARGER.** The distortion is specific to ensembling.")
    A("")
    A("### The trap in the implementation")
    A("")
    A("Two silent failure modes are handled in `tier1_ensemble.py`; both would quietly destroy the")
    A("result rather than error:")
    A("")
    A("1. **Sign.** Each pass has its own arbitrary gain *including polarity*. Averaging runs")
    A("   without sign matching lets opposite polarities **cancel the signal**. Every run is")
    A("   signed-least-squares projected onto run 0.")
    A("2. **Permutation.** Stream order is not stable across independent runs — speaker 1 in run 0")
    A("   can emerge as speaker 3 in run 1. Streams are Hungarian-matched on |cosine| first.")
    A("   (Note this is *across runs*; there is no permutation drift across *time* — see 1.4.)")
    A("")

# --------------------------------------------------------------- 1.4/1.7
A("## 1.4 Chunk stitching / permutation alignment — VERDICT: NOT A BUG, no work needed")
A("")
A("**Resolved by reading the source, no GPU required.** The roadmap flagged this as a possible")
A("live bug (\"speaker 1 in chunk A can emerge as speaker 3 in chunk B\"). It cannot happen:")
A("")
A("- `inference.py:process_waveform` → `engine_infer._single_pass_session` → `infer_chunk`")
A("  forwards the **entire STFT in one pass**. There is no chunking, therefore no stitching,")
A("  therefore no cross-boundary permutation drift.")
A("- The docstring agrees: *\"This release does not support CSS chunking; for long-form audio,")
A("  process in segments.\"*")
A("")
A("**The risk this leaves is different from the one the roadmap described.** Long audio is not")
A("*scrambled*; it is passed whole to a model trained on 4 s (`max_len: 32000` @ 8 kHz), which is")
A("untested. If the judge uses long audio, the open question is **quality degradation on long")
A("input**, and any segmenting *you* add would then introduce the permutation problem yourself.")
A("Still untested — an open risk.")
A("")
A("## 1.7 Input preprocessing — VERDICT: correct, no work needed")
A("")
A("Verified rather than assumed:")
A("")
A("- **Resampling anti-aliases properly.** `librosa.resample` defaults to `res_type='soxr_hq'`")
A("  (librosa 0.11.0). Probed with tones above the 4 kHz Nyquist: a 6 kHz tone resampled 16k→8k")
A("  comes back at **rms 0.0015**, and 7 kHz at **0.0007**, versus ~0.707 if they were aliasing —")
A("  ~54 dB of suppression. No naive decimation.")
A("- **Shape** is `(1, N)` for mono, as required.")
A("- **Normalization** is applied exactly once, internally, by `process_waveform`")
A("  (`waveform / (waveform.std(dim=-1, keepdim=True) + 1e-8)`). Callers must not pre-normalize.")
A("")

# ------------------------------------------------------------- reproduce
A("## What shipped, and how to use it")
A("")
A("`pipeline.py` is the shipping path (`Separator`), used by both `separate.py` and")
A("`benchmark.py`. Routing + MC are **ON by default in `separate.py`** and **OFF by default in")
A("`benchmark.py`** — deliberately: the bare `benchmark.py` command")
A("must keep reproducing the 23.39/23.84/22.20/20.57 baseline rather than silently change")
A("meaning.")
A("")
A("```bash")
A("python separate.py input.wav -o out/              # routing + MC on; writes manifest.json")
A("python separate.py input.wav -o out/ --no-route --no-mc   # plain baseline")
A("python benchmark.py --root data/wsj0_kmix --limit 100          # baseline (unchanged)")
A("python benchmark.py --root data/wsj0_kmix --limit 100 --route --mc   # with the wins")
A("```")
A("")
A("**Verified end-to-end, not just in the cache:** on the same 20 mixtures at N=2,")
A("`benchmark.py` gives **22.99 dB** default and **23.99 dB** with `--route --mc`, matching the")
A("caches exactly. `separate.py` on a 2-speaker mixture auto-routed to `fix-2spk-l-dm` with no")
A("hint, and the written audio has **crest factor 21.98/18.76 dB** (natural speech; ~2 dB would")
A("mean clipped) with **per-stream peaks that differ** (0.90 vs 0.80), confirming relative")
A("speaker levels survive the shared-gain rescale.")
A("")
A("**Routing infers N safely.** Routing needs the count *before* separating, and the count comes")
A("from the general model. That is sound because the built-in counter **never under-predicts**")
A("(0.0% below the diagonal over 2000 mixtures): predicted 2 ⇒ true ≤ 2 ⇒ true = 2.")
A("So a predicted 2 is trustworthy **even out of domain**, where raw N=2 counting accuracy is")
A("only 73%. Cost: one extra forward pass at RTF ~0.05 for 2-speaker input.")
A("")
A("## Reproduce / resume")
A("")
A("All runs are **resumable, and the reproduce command IS the resume command** — no `--resume`")
A("flag exists. Rerunning computes only what is missing; a fully-cached rerun costs a second")
A("because the check happens before the model loads. Raising `--limit` recomputes that count.")
A("")
A("```bash")
A("PY=SR_CorrNet_SS/.venv/Scripts/python.exe")
A("")
A("# 1.1 routing + 1.2 mixture consistency (both from one forward pass)")
A("$PY tier1_eval.py --repo shinuh/sr-corrnet-ss-1ch-wsj-var-2-5spk \\")
A("    --root data/wsj0_kmix --n-spks 2 3 4 5 --limit 100 --out cache_tier1/wsj0_var25.npz")
A("$PY tier1_eval.py --repo shinuh/sr-corrnet-ss-1ch-wsj-fix-2spk-l-dm \\")
A("    --root data/wsj0_kmix --n-spks 2 --limit 100 --out cache_tier1/wsj0_fix2ldm.npz")
A("$PY tier1_eval.py --repo shinuh/sr-corrnet-ss-1ch-wsj-fix-2spk \\")
A("    --root data/wsj0_kmix --n-spks 2 --limit 100 --out cache_tier1/wsj0_fix2.npz")
A("$PY tier1_eval.py --repo shinuh/sr-corrnet-ss-1ch-wsj-var-2-3spk \\")
A("    --root data/wsj0_kmix --n-spks 2 3 --limit 100 --out cache_tier1/wsj0_var23.npz")
A("$PY tier1_eval.py --repo shinuh/sr-corrnet-ss-1ch-wsj-var-2-5spk \\")
A("    --root data/libri_kmix_test --n-spks 2 3 4 5 --limit 100 --out cache_tier1/libri_var25.npz")
A("")
A("# 1.3 offset ensembling (+ the ens+MC stacking column). ~15 min GPU, 4x inference.")
A("$PY tier1_ensemble.py --root data/wsj0_kmix --n-spks 2 3 4 5 --limit 100 \\")
A("    --out cache_tier1/ensemble.npz")
A("")
A("# Sampling robustness check: --seed draws a RANDOM sample instead of the")
A("# alphabetically-first (which shares a leading speaker). Same seed => same")
A("# mixtures across checkpoints, so the comparison stays paired.")
A("$PY tier1_eval.py --repo shinuh/sr-corrnet-ss-1ch-wsj-var-2-5spk \\")
A("    --root data/wsj0_kmix --n-spks 2 3 4 5 --limit 100 --seed 1234 \\")
A("    --out cache_tier1/rand_var25.npz")
A("$PY tier1_eval.py --repo shinuh/sr-corrnet-ss-1ch-wsj-fix-2spk-l-dm \\")
A("    --root data/wsj0_kmix --n-spks 2 --limit 100 --seed 1234 \\")
A("    --out cache_tier1/rand_fix2ldm.npz")
A("")
A("# regenerate this document from the caches (CPU, seconds)")
A("$PY report_tier1.py")
A("```")
A("")
A("**Note `PYTHONIOENCODING=utf-8`** if printing these tables to a Windows console; the file")
A("itself is written with `encoding='utf-8'` and is immune.")
A("")
A("## Where the raw data lives")
A("")
A("| path | what |")
A("|---|---|")
A("| `cache_tier1/wsj0_*.npz` | per-mixture SI-SNRi (`base_N`, `mc_N`), keys, RTF — WSJ0 |")
A("| `cache_tier1/libri_var25.npz` | same, LibriSpeech dev-clean (out of domain) |")
A("| `cache_tier1/rand_*.npz` | the `--seed 1234` random-sample robustness check |")
A("| `cache_tier1/ensemble.npz` | per-mixture `single_N`/`ens_N`/`ensmc_N` — **n=100 at N=2/3/4, n=25 at N=5** |")
A("| `pipeline.py` | **the shipping path**: routing table + mixture consistency + safe rescale |")
A("| `probe_output_scale.py` | evidence for the output-gain finding in 1.2 (~30 s GPU) |")
A("| `tier1_eval.py` | routing + MC harness (resumable, atomic) |")
A("| `tier1_ensemble.py` | offset ensembling (resumable, atomic) |")
A("| `report_tier1.py` | regenerates this file from the caches |")
A("")
A("Per-mixture arrays are keyed by filename, so any pair of caches can be re-compared paired")
A("without touching the GPU.")
A("")
A("## Sampling — the default subset is NOT random, and it was checked")
A("")
A("Every table above except this section uses `sorted(keys)[:limit]`, matching `benchmark.py`")
A("and the verified baseline (so the numbers stay comparable). **That")
A("is not a random sample:** WSJ0-mix keys lead with a speaker id, so all 100 mixtures share a")
A("leading speaker (`050`). The `tt` set has only **16 distinct speakers total**, and the first")
A("100 keys do cover all 16 — so the subset is less degenerate than it first looks, but it is")
A("still a biased 100 of 3000.")
A("")
A("**The two shipped wins were re-measured on a random sample and both got LARGER**")
A("(`--seed 1234`, n=100, paired):")
A("")
A("| measurement | sorted prefix | random sample |")
A("|---|---|---|")
if (C / "rand_var25.npz").exists() and (C / "rand_fix2ldm.npz").exists():
    rv, rl = load("rand_var25.npz"), load("rand_fix2ldm.npz")
    lv = load("wsj0_fix2ldm.npz")
    _, _, ds, cis, _, _ = paired(var25, lv, 2)
    _, _, dr, cir, pr, _ = paired(rv, rl, 2)
    A(f"| routing, `l-dm` vs `var-2-5spk` @ N=2 | {ds:+.3f} ±{cis:.3f} | **{dr:+.3f} ±{cir:.3f}** (p={fmt(pr)}) |")
    for n in (2, 3, 4, 5):
        if f"mc_{n}" not in rv:
            continue
        _, _, d1, c1, _, _ = paired(var25, var25, n, "base", "mc")
        _, _, d2, c2, _, _ = paired(rv, rv, n, "base", "mc")
        A(f"| mixture consistency @ N={n} | {d1:+.3f} ±{c1:.3f} | **{d2:+.3f} ±{c2:.3f}** |")
A("")
A("**Verdict: the shipped wins are robust to sampling** — the sorted subset was if anything")
A("mildly *conservative* about them. The small-sample distortion documented in 1.3 is specific")
A("to ensembling's heavy-tailed deltas, not a flaw in the routing or MC results.")
A("")
A("Note the *absolute* baseline differs between subsets (N=2 base 23.39 sorted vs 23.98 random),")
A("i.e. the sorted subset is slightly harder. **Absolute numbers are subset-dependent; the")
A("paired deltas are what transfer.**")
A("")
A("## Precision — what these numbers do and do not support")
A("")
A("At n=100 paired, the CIs are **±0.01–0.15 dB** for MC and **±0.15–0.78 dB** for routing")
A("(routing CIs are wider because two different checkpoints disagree per-mixture far more than")
A("one checkpoint disagrees with itself).")
A("")
A("- **Ample** for the +0.57 dB routing win and every MC row.")
A("- **Do not read the third decimal.**")
A("- **Every table is now n=100.** The ensemble's n=25 pass overestimated at every count (1.3);")
A("  those figures are superseded and must not be quoted.")
A("- All WSJ0 numbers are **in domain**. The `-l-dm` routing win is measured on WSJ0 only and")
A("  **was not tested out of domain** — if the judge's audio is not WSJ0-like, it is unverified.")
A("")
A("## Bottom line")
A("")
A("**Confirmed, shipped, and verified end-to-end: +1.00 dB at N=2**, +0.19 at N=3, +0.08 at N=4,")
A("+0.04 at N=5 — **at no extra inference cost.** Measured through the shipping path on identical")
A("mixtures: `benchmark.py --n-spks 2 --limit 20` gives **22.99 dB** by default and **23.99 dB**")
A("with `--route --mc`, both reproducing the caches exactly.")
A("")
A("**Offset ensembling is real but marginal, and deliberately NOT shipped.** Measured at n=100")
A("across all counts, *over mixture consistency alone*, it is worth **nothing at N=2, +0.21 at")
A("N=3, +0.39 at N=4, +0.44 at N=5** — for **4× inference**. The gain grows with N (the mirror")
A("image of MC), consistent with an SAR/artifact error that partly cancels under averaging. It")
A("is left out because 4× inference for ≤0.44 dB is an RTF-budget tradeoff only the judge's")
A("constraints can settle; `tier1_ensemble.py` implements it if that changes.")
A("")
A("This is well short of the roadmap's \"+1 to +3 dB\" estimate for Tier 1, and the shape of the")
A("result says why: **three of four routing bets lost; the one that won looks like a dynamic")
A("mixing effect rather than a specialization effect; ensembling survives only at N≥3 and only")
A("at 4× inference; and 1.4 and 1.7 — two of the seven items — turned out to be non-problems**")
A("that cost nothing but were worth nothing. Tier 1 is close to exhausted. The remaining")
A("leverage is **Tier 0** (what does")
A("the judge actually test on — worth up to 9 dB, and gates everything) and **Tier 2.1**")
A("(fine-tune with DM on), which the `-l-dm` result now independently supports: the only")
A("checkpoint that beat the general model is the dynamic-mixing one.")

pathlib.Path("results_tier1.md").write_text("\n".join(L) + "\n", encoding="utf-8")
print(f"wrote results_tier1.md ({len(L)} lines)")
